### ISSUE TITLE
You have been Obadified

### ISSUE THREAD

**Issue by Ahmad-Mtr** [opadasaleh/our-project#1]
Use `gitignore` if u don't want to put `.docx` in the remote repo.

In your terminal assuming you already navigated to the repo's folder:

```sh
ni .gitignore
```
Then write the name of all of your files that you want git to ignore them.

Then commit & push .

Enjoy

**Comment by opadasaleh** [comment]
```
ni .gitignore
``` 
what ni ?

**Comment by Ahmad-Mtr** [comment]
`New-Item .gitignore`
A powershell command to create a new file named `.gitignore`.
